name: dart_web3gas
description: Calculate gas fees based on web3art. Refer to metamask for the calculation method.
version: 0.0.2
homepage: https://github.com/randsoy/dart_web3gas

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  logger: ^1.3.0
  json_annotation: ^4.8.0
  json_serializable: "^6.6.1"
  http: ^0.13.5
  eip55: ^1.0.2
  stream_channel: "^2.1.1"
  stream_transform: "^2.1.0"
  json_rpc_2: ^3.0.2
  uuid: ^3.0.7
  convert: ^3.1.1
  sec: ^1.1.0
  pointycastle: ^3.7.1
  typed_data: ^1.3.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.19.0
  build_runner: "^2.0.0"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.